### ISSUE TITLE
Wrong username on github-readme-streak-stats

### ISSUE THREAD

**Issue by AkshayAshokCode** [Jparrgam/jparrgam#1]
The username used for GitHub-readme-streak-stats is mine instead of yours.
You can fix it by replacing `AkshayAshokCode` with `jparrgam` in the below line

`<p><img align="center" src="https://github-readme-streak-stats.herokuapp.com/?user=AkshayAshokCode&theme=github-dark&hide_border=true" alt="AkshayAshokCode"/></p>`

I would highly appreciate it if you can also ⭐ my GitHub's readme if you liked it.

Thanks @Jparrgam

**Comment by Jparrgam** [comment]
Hi @AkshayAshokCode thanks for report
